### ISSUE TITLE
Test sets

### ISSUE THREAD

**Issue by tltsilveira** [ShahinSHH/COVID-CT-MD#3]
Thank you for sharing the dataset.

I suppose that this dataset is the one used in IEEE ICASSP SPGC. Am I right?

If so, could you please provide the ground-truth labels for the three test sets or at least allow access to an application to analyze our method's performance?

Many thanks for considering my request.

Best, 

Thiago L T da Silveira.

**Comment by ShahinSHH** [comment]
Hello, thanks for your message and interest in this dataset. I can share the three test sets with you if you provide me your email address. Unfortunately, I can't share the ground truths at the moment. We are in the process of providing an automatic evaluation tool so that you can evaluate your model's performance there. It's in its final steps and will be launched shortly.

**Comment by ShahinSHH** [comment]
> Thank you for sharing the dataset.
> 
> I suppose that this dataset is the one used in IEEE ICASSP SPGC. Am I right?
> 
> If so, could you please provide the ground-truth labels for the three test sets or at least allow access to an application to analyze our method's performance?
> 
> Many thanks for considering my request.
> 
> Best,
> 
> Thiago L T da Silveira.

**Comment by ShahinSHH** [comment]
Meanwhile, if you need the results for your research study or project, you are welcome to send your model's output to me (the prediction classes in three separate CSV files). I will send you back your model's performance.
